dist: trusty
language: php
sudo: required

php:
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - LIBRDKAFKA_VERSION=v0.11.3

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - chmod +x .ci/install_rdkafka.sh

install:
  - .ci/install_rdkafka.sh
  - travis_retry composer update --prefer-dist

script: ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: nightly
    - env: DEV_DEPENDENCIES

  include:
    - stage: Test
      env: LOWEST_DEPENDENCIES
      install:
        - .ci/install_rdkafka.sh
        - travis_retry composer update -n --prefer-dist --prefer-lowest

    - stage: Test
      env: LOWEST_DEPENDENCIES
      php: 7.2
      install:
        - .ci/install_rdkafka.sh
        - travis_retry composer update -n --prefer-dist --prefer-lowest

    - stage: Test
      env: LOWEST_DEPENDENCIES
      php: nightly
      install:
        - .ci/install_rdkafka.sh
        - travis_retry composer update -n --prefer-dist --prefer-lowest

    - stage: Test
      env: DEV_DEPENDENCIES
      php: nightly
      install:
        - .ci/install_rdkafka.sh
        - composer config minimum-stability dev
        - travis_retry composer update -n --prefer-dist

    - stage: Test
      env: COVERAGE
      php: 7.1
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: Coding standard
      script:
        - ./vendor/bin/phpcs

    - stage: Static Analysis
      script:
        - ./vendor/bin/phpstan analyse -c phpstan.neon -l max src

cache:
  directories:
    - $HOME/.composer/cache
